import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
size = 16

[font.normal]
family = "Hack Nerd Font"

[window]
opacity = 0.99
decorations = "None"
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10